### ISSUE TITLE
Missing Rig Controller options

### ISSUE THREAD

**Issue by difreo** [NickTiny/tiny_2d_rig_tools#3]
After initializing armature in Tiny Rig Controller tab only appears : Pose Head, Pose, Mouth and L Arm. Nothing else. Blender 3.6 and 4.2. in 4.2 IK is not working at all.

**Comment by NickTiny** [comment]
Are you enabling all the options in the operator pop up in 3.3?

The addon doesn’t support 3.6 or 4.2 at this time I have not had time work on this project

**Comment by difreo** [comment]
Unfortunately no luck. In 4.2 i think it is completetly broken but in 3.3 the issue is this:
`Python: Traceback (most recent call last):
  File "...\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\tiny_2d_rig_tools\rig_control\ui.py", line 146, in draw
    self.draw_limb_column(left_col, self.rig_prefs.l_side)
  File "...\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\tiny_2d_rig_tools\rig_control\ui.py", line 70, in draw_limb_column
    if bone.id_data.tiny_rig.set_appendage_flip:
AttributeError: 'RIGCONTROL_settings' object has no attribute 'set_appendage_flip'
`

**Comment by NickTiny** [comment]
And what steps can I use to reproduce this error?

What operations did you run, are you running this in the armature the add-on creates for example?

I am on vacation right now but I’ll try to look at this next week so as much information as possible so I can reproduce the error would be appreciated.
